// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// Document generated: 2024-08-01 16:15:30.123456

export const firebaseConfig = {
  "apiKey": "AIzaSyD_qHaYdVYh4VrE2ryDmlJSqL61ha7A1D8",
  "authDomain": "studio-3067503220-b7d50.firebaseapp.com",
  "projectId": "studio-3067503220-b7d50",
  "storageBucket": "studio-3067503220-b7d50.firebasestorage.app",
  "messagingSenderId": "959904790225",
  "appId": "1:959904790225:web:2bd6934ed297c37eacf7f0"
};
