// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// Document generated: 2024-08-01 15:42:36.431055

export const firebaseConfig = {
  "apiKey": "YOUR_API_KEY",
  "authDomain": "YOUR_AUTH_DOMAIN",
  "projectId": "YOUR_PROJECT_ID",
  "storageBucket": "YOUR_STORAGE_BUCKET",
  "messagingSenderId": "YOUR_MESSAGING_SENDER_ID",
  "appId": "YOUR_APP_ID"
};
